### ISSUE TITLE
Error: 'req_perform_stream' is not an exported object from 'namespace:httr2'

### ISSUE THREAD

**Issue by wenbopeng** [hauselin/ollama-r#4] opened 2024-06-21 12:58 UTC
ollamar version 1.1.1

```R
### ** Examples

## Don't show: 
if (test_connection()$status_code == 200) (if (getRversion() >= "3.4") withAutoprint else force)({ # examplesIf
## End(Don't show)
generate("llama3", "The sky is...", stream = FALSE, output = "df")
generate("llama3", "The sky is...", stream = TRUE, output = "df")
generate("llama3", "The sky is...", stream = FALSE, output = "jsonlist")
## Don't show: 
}) # examplesIf

```

```text
Ollama local server running
> generate("llama3", "The sky is...", stream = FALSE, output = "df")
<httr2_response>
POST http://127.0.0.1:11434/api/generate
Status: 200 OK
Content-Type: application/json
Body: In memory (346 bytes)
# A tibble: 1 × 3
  model  response created_at                  
  <chr>  <chr>    <chr>                       
1 llama3 Blue!    2024-06-21T12:54:20.4342404Z
> generate("llama3", "The sky is...", stream = TRUE, output = "df")
Error: 'req_perform_stream' is not an exported object from 'namespace:httr2'
## End(Don't show)
```

**Comment by hauselin** [comment] 2024-07-01 00:54
I can't reproduce this error. When I run the line that produced the error you reported, the correct output is produced. Could you provide more details so I can debug? Thanks!

```r
> packageVersion("ollamar")
[1] ‘1.1.1’
> generate("llama3", "The sky is...", stream = TRUE, output = "df")
Blue!

# A tibble: 3 × 3
  model  response created_at                 
  <chr>  <chr>    <chr>                      
1 llama3 "Blue"   2024-07-01T00:52:42.68694Z 
2 llama3 "!"      2024-07-01T00:52:42.709517Z
3 llama3 ""       2024-07-01T00:52:42.728993Z

```

**Comment by xiaoluolorn** [comment] 2024-07-14 03:49
Maybe this can be resolved by update the  package "httr2".

**Comment by hauselin** [comment] 2024-07-14 16:07
Thanks! I'll close this issue for now if upgrading httr2 resolves the problem. Reopen this issue if there are further issues.

**Closed as completed by hauselin** 2024-07-14 16:07 UTC

**Comment by wenbopeng** [comment] 2024-07-15 08:29
> generate("llama3", "The sky is...", stream = FALSE, output = "df")

Perfect solution to the issue, thank you!

**Comment by wenbopeng** [comment] 2024-07-15 08:30
> Maybe this can be resolved by update the package "httr2".

Perfect solution to the issue, thank you!
